Repository gladguys/polis, pull requests merged in 2020-05, with the labels that each got.

#218 Small improves
  lib/extension/media_query_extensions.dart
  lib/page/crunching_data/crunching_data_page.dart
  lib/page/intro/intro_page.dart
  lib/page/politic_profile/widget/politic_activities.dart
  lib/page/signup/signup_page.dart
  lib/page/user_profile/widget/activities_list.dart
  lib/page/user_profile/widget/personal_user_info.dart
Labels: waiting review, waiting tester

#223 Fix 123
  assets/images/empty.png
  lib/core/constants.dart
  lib/i18n/message.dart
  lib/page/crunching_data/crunching_data_page.dart
  lib/page/favorite_posts/favorite_posts_page.dart
  lib/page/politic_followers/politic_followers_page.dart
  lib/widget/empty_info.dart
  lib/widget/error_container.dart
  test/service/ad_service_test.dart
  test/widget/empty_info_test.dart
  test/widget/page/favorite_posts_page_test.dart
  test/widget/page/politic_followers_page_test.dart
Labels: bug, waiting review, waiting tester

#224 fixing bug
  lib/repository/concrete/firebase/firebase_timeline_repository.dart
  test/repository/firebase_timeline_repository_test.dart
Labels: bug, waiting review, waiting tester

#226 ads alternative
  android/app/src/main/AndroidManifest.xml
  lib/core/service/ad_service.dart
  lib/core/service/locator.dart
  lib/core/service/services.dart
  lib/main.dart
  lib/page/timeline/widget/timeline.dart
  pubspec.lock
  pubspec.yaml
  test/mock.dart
  test/service/ad_service_test.dart
Labels: debate first, enhancement, waiting tester

#234 adjusting back button in some pages
  lib/page/politic_profile/politic_profile_page.dart
  lib/page/user_following_politics/user_following_politics_page.dart
  lib/page/user_profile/user_profile_page.dart
  lib/widget/default_bottombar.dart
Labels: enhancement, waiting review, waiting tester

#233 Enhacement 219
  assets/animations/PolisIntro.flr
  assets/animations/PolisLoading.flr
  lib/extension/extensions.dart
  lib/extension/formatter_extensions.dart
  lib/extension/time_extensions.dart
  lib/i18n/label.dart
  lib/i18n/message.dart
  lib/page/crunching_data/crunching_data_page.dart
  lib/page/crunching_data/widget/searching_info.dart
  lib/page/politic_profile/widget/politic_activities.dart
  lib/page/search_politic/widgets/search_politics.dart
  lib/page/signup/signup_page.dart
  lib/page/tramitacao_proposta/tramitacao_proposta_page.dart
  lib/page/user_profile/widget/activities_list.dart
  lib/widget/post/post_despesa.dart
  lib/widget/post/post_proposta.dart
  lib/widget/tile/despesa_tile.dart
  lib/widget/tile/proposta_tile.dart
  test/widget/page/crunching_data_page_test.dart
  test/widget/page/signup_page_test.dart
Labels: enhancement, pending ui, waiting review, waiting tester

#212 Feature 211
  lib/bloc/tramitacao_proposta/tramitacao_proposta_bloc.dart
  lib/core/service/orgao_service.dart
  lib/core/service/services.dart
  lib/core/service/shared_preferences_service.dart
  lib/i18n/label.dart
  lib/main.dart
  lib/model/models.dart
  lib/model/orgao_model.dart
  lib/page/theme/main_theme.dart
  lib/page/tramitacao_proposta/tramitacao_proposta_page.dart
  lib/page/tramitacao_proposta/tramitacao_proposta_page_connected.dart
  lib/repository/abstract/orgao_repository.dart
  lib/repository/abstract/sync_log_repository.dart
  lib/repository/concrete/firebase/firebase.dart
  lib/repository/concrete/firebase/firebase_orgao_repository.dart
  lib/repository/concrete/firebase/firebase_sync_log_repository.dart
  lib/repository/concrete/hive/box.dart
  lib/repository/concrete/hive/hive_orgao_repository.dart
  lib/repository/concrete/repositories.dart
  lib/widget/label_value.dart
  lib/widget/my_app_injections.dart
  test/bloc/tramitacao_proposta_bloc_test.dart
  test/mock.dart
  test/model/orgao_model_test.dart
  test/repository/firebase_orgao_repository_test.dart
  test/repository/firebase_sync_log_repository_test.dart
  test/repository/hive_orgao_repository_test.dart
  test/service/orgao_service_test.dart
  test/service/shared_preferences_service_test.dart
  test/widget/page/tramitacao_proposta_page_test.dart
Labels: feature, waiting review, waiting tester

#242 Cloud function order
  functions/index.js
  functions/lib/onCreateActivity.js
  functions/lib/onCreateFavoriteActivity.js
  functions/lib/onCreateFollower.js
  functions/lib/onDeleteFavoriteActivity.js
  functions/lib/onDeleteFollower.js
  functions/lib/onUpdateUser.js
  lib/repository/concrete/firebase/firebase_edit_profile_repository.dart
  lib/repository/concrete/firebase/firebase_signup_repository.dart
  test/repository/firebase_edit_profile_repository_test.dart
  test/repository/firebase_signup_repository_test.dart
Labels: enhancement, waiting review, waiting tester

#244 trocando slidepanel do perfil do politico
  lib/page/politic_profile/widget/politic_activities.dart
  lib/page/politic_profile/widget/politic_profile.dart
  lib/page/user_profile/widget/activities_list.dart
  lib/page/user_profile/widget/logout_button.dart
  lib/page/user_profile/widget/user_activities.dart
  lib/page/user_profile/widget/user_profile.dart
  pubspec.lock
  pubspec.yaml
  test/widget/logout_button_test.dart
  test/widget/page/user_profile_page_test.dart
Labels: waiting tester

#238 criando logica de somador de despesas
  functions/index.js
  lib/extension/formatter_extensions.dart
  lib/model/politico_model.dart
  lib/page/politic_profile/widget/politic_additional_info.dart
  test/model/politico_model_test.dart
Labels: WIP, enhancement, waiting tester

#243 Enhacement 236
  lib/bloc/timeline/timeline_bloc.dart
  lib/bloc/timeline/timeline_event.dart
  lib/bloc/timeline/timeline_state.dart
  lib/core/keys.dart
  lib/i18n/label.dart
  lib/model/proposta_model.dart
  lib/page/timeline/timeline_page.dart
  lib/page/timeline/widget/timeline.dart
  lib/repository/concrete/firebase/firebase_timeline_repository.dart
  lib/widget/loading.dart
  lib/widget/post/post_proposta.dart
  lib/widget/tile/proposta_tile.dart
  pubspec.lock
  pubspec.yaml
  test/bloc/event/timeline_event_test.dart
  test/bloc/flutter_bloc_delegate_test.dart
  test/bloc/state/timeline_state_test.dart
  test/bloc/timeline_bloc_test.dart
  test/model/orgao_model_test.dart
  test/model/politico_model_test.dart
  test/model/proposta_model_test.dart
  test/repository/hive_orgao_repository_test.dart
  test/widget/page/favorite_posts_page_test.dart
  test/widget/page/politic_profile_page_test.dart
  test/widget/page/post_page_test.dart
  test/widget/page/timeline_page_test.dart
  test/widget/page/tramitacao_proposta_page_test.dart
  test/widget/post_proposta_test.dart
  test/widget/proposta_tile_test.dart
Labels: enhancement, waiting tester

#255 improving design
  lib/widget/select/estado_select.dart
  lib/widget/select/partido_select.dart
Labels: enhancement

#259 Fix timeline fetch more
  lib/core/constants.dart
  lib/enum/timeline_status.dart
  lib/page/timeline/timeline_page.dart
  lib/page/timeline/widget/timeline.dart
  test/widget/page/timeline_page_test.dart
Labels: bug, pending tests, waiting tester

#276 reajustando functions
  functions/lib/onCreateActivity.js
Labels: waiting review

#279 melhorando card despesa
  lib/i18n/label.dart
  lib/widget/post/post_despesa.dart
  lib/widget/post/post_proposta.dart
  lib/widget/tile/proposta_tile.dart
  test/widget/page/timeline_page_test.dart
Labels: WIP, pending tests

#281 Improve timeline scroll loading
  lib/page/timeline/timeline_page.dart
  lib/page/timeline/widget/timeline.dart
  test/widget/page/timeline_page_test.dart
Labels: waiting review, waiting tester

#293 Enhacement 284
  functions/lib/onCreateFollower.js
Labels: waiting review

#294 Enhacement 292
  functions/lib/onCreateActivity.js
  lib/repository/concrete/firebase/firebase.dart
  lib/repository/concrete/firebase/firebase_politic_profile_repository.dart
  lib/repository/concrete/firebase/firebase_timeline_repository.dart
  test/repository/firebase_politic_profile_repository_test.dart
  test/repository/firebase_timeline_repository_test.dart
Labels: pending tests

#299 mudanças (PARA DEBATERMOS)
  functions/lib/onCreateActivity.js
  lib/i18n/label.dart
  lib/page/tramitacao_proposta/tramitacao_proposta_page.dart
Labels: enhancement, pending ui

#301 Feature 300
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/mipmap-hdpi/ic_stat_account_balance.png
  android/app/src/main/res/mipmap-hdpi/ic_stat_p.png
  android/app/src/main/res/mipmap-mdpi/ic_stat_account_balance.png
  android/app/src/main/res/mipmap-mdpi/ic_stat_p.png
  android/app/src/main/res/mipmap-xhdpi/ic_stat_account_balance.png
  android/app/src/main/res/mipmap-xhdpi/ic_stat_p.png
  android/app/src/main/res/mipmap-xxhdpi/ic_stat_account_balance.png
  android/app/src/main/res/mipmap-xxhdpi/ic_stat_p.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_stat_account_balance.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_stat_p.png
  android/app/src/main/res/values/colors.xml
  android/settings_aar.gradle
  lib/bloc/signin/signin_bloc.dart
  lib/core/service/locator.dart
  lib/core/service/message_service.dart
  lib/core/service/services.dart
  lib/main.dart
  lib/model/user_model.dart
  lib/page/initial/initial_page_connected.dart
  lib/page/signin/signin_page_connected.dart
  lib/repository/concrete/firebase/firebase.dart
  pubspec.lock
  pubspec.yaml
  test/bloc/flutter_bloc_delegate_test.dart
  test/bloc/signin_bloc_test.dart
  test/mock.dart
  test/model/user_model_test.dart
  test/service/message_service_test.dart
Labels: feature, waiting review

#298 Enhacement 295
  lib/model/despesa_model.dart
  lib/model/politico_model.dart
  lib/model/proposta_model.dart
  lib/page/politic_profile/widget/politic_personal_info.dart
  lib/widget/tile/despesa_tile.dart
  lib/widget/tile/proposta_tile.dart
  test/model/despesa_model_test.dart
  test/model/politico_model_test.dart
  test/model/proposta_model_test.dart
  test/widget/despesa_tile_test.dart
  test/widget/page/favorite_posts_page_test.dart
  test/widget/page/politic_profile_page_test.dart
  test/widget/page/timeline_page_test.dart
  test/widget/proposta_tile_test.dart
Labels: enhancement, pending ui, waiting review

#303 Enhacement 302
  lib/i18n/label.dart
  lib/model/politico_model.dart
  lib/page/politic_profile/widget/politic_additional_info.dart
  test/model/politico_model_test.dart
Labels: enhancement, pending ui, waiting tester

#304 Enhacement 297
  lib/i18n/label.dart
  lib/model/proposta_model.dart
  lib/widget/tile/despesa_tile.dart
  lib/widget/tile/proposta_tile.dart
  lib/widget/timeline_card_label.dart
  test/model/proposta_model_test.dart
  test/widget/page/timeline_page_test.dart
Labels: enhancement, pending ui, waiting review, waiting tester

#330 changing app name
  android/app/src/main/AndroidManifest.xml
Labels: enhancement

#328 Enhacement 321
  lib/core/utils/date_utils.dart
  lib/i18n/label.dart
  lib/i18n/message.dart
  lib/page/politic_profile/widget/politic_additional_info.dart
  test/core/utils/date_utils_test.dart
Labels: enhancement

#332 Bugfix 331
  lib/bloc/post/post_bloc.dart
  lib/bloc/post/post_event.dart
  lib/page/post/post_page_connected.dart
  lib/repository/abstract/post_repository.dart
  lib/repository/concrete/firebase/firebase_post_repository.dart
  test/bloc/event/post_event_test.dart
  test/bloc/post_bloc_test.dart
  test/widget/favorite_proposta_tile_test.dart
Labels: bug

#333 correcting the splash
  android/app/src/main/res/drawable-hdpi/splash.png
  android/app/src/main/res/drawable-mdpi/splash.png
  android/app/src/main/res/drawable-xhdpi/splash.png
  android/app/src/main/res/drawable-xxhdpi/splash.png
  android/app/src/main/res/drawable-xxxhdpi/splash.png
  android/app/src/main/res/values/styles.xml
  assets/images/logo_splash.png
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png
  ios/Runner/Base.lproj/LaunchScreen.storyboard
  pubspec.yaml
Labels: enhancement

#338 ordering by name
  lib/repository/concrete/firebase/firebase.dart
  lib/repository/concrete/firebase/firebase_politico_repository.dart
  test/repository/firebase_politico_repository_test.dart
Labels: enhancement

#339 correcting cloud function
  functions/lib/onCreateFollower.js
  functions/lib/onDeleteFollower.js
Labels: bug

#334 adjusting sort order
  lib/repository/concrete/firebase/firebase_tramitacao_proposta_repository.dart
  test/repository/firebase_tramitacao_proposta_repository_test.dart
Labels: enhancement

#348 Feature 347
  lib/core/service/app_update_service.dart
  lib/core/service/locator.dart
  lib/core/service/services.dart
  lib/i18n/label.dart
  lib/i18n/message.dart
  lib/page/crunching_data/crunching_data_page.dart
  lib/page/initial/initial_page.dart
  lib/page/signin/signin_page.dart
  lib/page/timeline/timeline_page_connected.dart
  lib/widget/default_bottombar.dart
  lib/widget/my_app.dart
  lib/widget/update_app_dialog.dart
  pubspec.lock
  pubspec.yaml
  test/mock.dart
  test/widget/default_bottombar_test.dart
  test/widget/page/crunching_data_page_test.dart
  test/widget/page/timeline_page_test.dart
Labels: feature, pending tests, waiting review, waiting tester

#352 Enhacement 346
  lib/core/keys.dart
  lib/main.dart
  lib/page/politic_profile/politic_profile_page.dart
  lib/page/politic_profile/politic_profile_page_connected.dart
  lib/page/politic_profile/widget/politic_action_buttons.dart
  lib/page/politic_profile/widget/politic_additional_info.dart
  lib/page/politic_profile/widget/politic_profile.dart
  lib/page/search_politic/widgets/search_politics_list.dart
  lib/page/user_following_politics/widget/following_politics_list.dart
  lib/widget/my_app.dart
  test/widget/following_politics_list_test.dart
  test/widget/my_app_test.dart
  test/widget/politic_action_buttons_test.dart
  test/widget/politic_additional_info_test.dart
Labels: enhancement, waiting review, waiting tester

#350 adding labels indicating start and end on tramitations
  lib/i18n/label.dart
  lib/page/tramitacao_proposta/tramitacao_proposta_page.dart
  lib/widget/timeline_tile.dart
  lib/widget/update_app_dialog.dart
Labels: enhancement, pending tests, waiting review, waiting tester

#351 adjusting timeline ad
  lib/extension/extensions.dart
  lib/extension/theme_extensions.dart
  lib/page/crunching_data/crunching_data_page.dart
  lib/page/crunching_data/widget/searching_info.dart
  lib/page/edit_profile/edit_profile_page.dart
  lib/page/timeline/widget/timeline.dart
  lib/widget/ad/timeline_ad_banner.dart
  lib/widget/post/post_despesa.dart
  lib/widget/post/post_proposta.dart
  test/widget/page/timeline_page_test.dart
Labels: enhancement, pending ui

#361 Enhacement 358
  lib/model/despesa_model.dart
  lib/model/proposta_model.dart
  lib/repository/concrete/firebase/firebase.dart
  lib/repository/concrete/firebase/firebase_politic_profile_repository.dart
  lib/repository/concrete/firebase/firebase_timeline_repository.dart
  test/model/despesa_model_test.dart
  test/repository/firebase_politic_profile_repository_test.dart
  test/repository/firebase_timeline_repository_test.dart
Labels: enhancement

#365 enhacement 364
  lib/core/keys.dart
  lib/i18n/label.dart
  lib/model/proposta_model.dart
  lib/page/politic_profile/widget/politic_additional_info.dart
  lib/widget/general/proposal_authors.dart
  lib/widget/post/post_proposta.dart
  test/model/proposta_model_test.dart
  test/widget/general/proposal_authors_test.dart
  test/widget/page/post_page_test.dart
  test/widget/post_proposta_test.dart
Labels: enhancement
