Repository gladguys/polis, pull requests merged in 2020-04, with the labels that each got.

#111 sending events to analytics
  lib/bloc/flutter_bloc_delegate.dart
  lib/core/service/analytics_service.dart
  lib/main.dart
  test/bloc/flutter_bloc_delegate_test.dart
  test/service/analytics_service_test.dart
Labels: enhancement

#105 Feature 80
  lib/bloc/blocs.dart
  lib/bloc/post/bloc.dart
  lib/bloc/post/post_bloc.dart
  lib/bloc/post/post_event.dart
  lib/bloc/post/post_state.dart
  lib/core/routing/route_names.dart
  lib/enum/post_type.dart
  lib/i18n/label.dart
  lib/page/pages.dart
  lib/page/politic_profile/widget/politic_additional_info.dart
  lib/page/post/post_page.dart
  lib/page/post/post_page_connected.dart
  lib/page/timeline/widget/goto_post_gesture_detector.dart
  lib/page/timeline/widget/timeline.dart
  lib/repository/abstract/post_repository.dart
  lib/repository/concrete/firebase/firebase_post_repository.dart
  lib/repository/concrete/repositories.dart
  lib/widget/default_bottombar.dart
  lib/widget/my_app_injections.dart
  lib/widget/tile/despesa_tile.dart
  pubspec.lock
  pubspec.yaml
  test/bloc/event/post_event_test.dart
  test/bloc/post_bloc_test.dart
  test/bloc/state/post_state_test.dart
  test/mock.dart
  test/repository/firebase_post_repository_test.dart
  test/widget/default_bottombar_test.dart
  test/widget/goto_post_gesture_detector_test.dart
  test/widget/page/post_page_test.dart
  test/widget/page/timeline_page_test.dart
  test/widget/personal_user_info_test.dart
  test/widget/politic_additional_info_test.dart
Labels: feature

#132 not comitting *g files
  .gitignore
  lib/model/despesa_model.g.dart
  lib/model/partido_model.g.dart
  lib/model/politico_model.g.dart
  lib/model/proposta_model.g.dart
  lib/model/user_model.g.dart
  lib/model/usuario_seguindo_politico_model.g.dart
Labels: enhancement, waiting review

#133 Enhacement 122
  lib/model/proposta_model.dart
  lib/page/post/post_page.dart
  lib/widget/tile/despesa_tile.dart
  lib/widget/tile/proposta_tile.dart
  test/widget/despesa_tile_test.dart
  test/widget/page/post_page_test.dart
  test/widget/proposta_tile_test.dart
Labels: enhancement, waiting review

#135 Feature 134
  lib/bloc/politic_profile/politic_profile_bloc.dart
  lib/bloc/politic_profile/politic_profile_event.dart
  lib/bloc/politic_profile/politic_profile_state.dart
  lib/core/constants.dart
  lib/core/service/locator.dart
  lib/core/service/services.dart
  lib/core/service/url_launcher_service.dart
  lib/core/validators.dart
  lib/page/politic_profile/politic_profile_page.dart
  lib/page/politic_profile/politic_profile_page_connected.dart
  lib/page/politic_profile/widget/politic_action_buttons.dart
  lib/page/search_politic/search_politic_page_connected.dart
  pubspec.lock
  pubspec.yaml
  test/bloc/event/politic_profile_event_test.dart
  test/bloc/politic_profile_bloc_test.dart
  test/bloc/state/politic_profile_state_test.dart
  test/core/validators_test.dart
  test/mock.dart
  test/service/url_launcher_service_test.dart
  test/widget/page/politic_profile_page_test.dart
  test/widget/politic_action_buttons_test.dart
Labels: feature, waiting review

#142 ordering partidos for sigle
  lib/widget/select/partido_select.dart
Labels: enhancement, waiting review

#143 ordering descending
  lib/repository/concrete/firebase/firebase_politic_profile_repository.dart
  test/repository/firebase_politic_profile_repository_test.dart
Labels: enhancement, waiting review

#144 Enhacement 139
  lib/bloc/search_politic/search_politic_bloc.dart
  pubspec.lock
  pubspec.yaml
  test/bloc/search_politic_bloc_test.dart
Labels: enhancement, waiting review

#141 Bugfix 137
  lib/bloc/search_politic/search_politic_bloc.dart
  lib/bloc/search_politic/search_politic_state.dart
  test/bloc/search_politic_bloc_test.dart
  test/bloc/state/search_politic_state_test.dart
  test/widget/page/search_politic_page_test.dart
Labels: bug, waiting tester

#136 Feature cloudfun add atividade timeline
  functions/index.js
Labels: WIP

#151 making image not clickable on profile page
  lib/page/politic_profile/widget/politic_activities.dart
  lib/widget/tile/despesa_tile.dart
  lib/widget/tile/despesa_tile_connected.dart
  lib/widget/tile/proposta_tile.dart
  lib/widget/tile/proposta_tile_connected.dart
Labels: waiting review, waiting tester

#156 Bugfix 154
  lib/repository/concrete/hive/hive_partido_repository.dart
  lib/repository/concrete/hive/hive_politico_repository.dart
  test/repository/hive_partido_repository_test.dart
  test/repository/hive_politico_repository_test.dart
Labels: bug, waiting review, waiting tester

#155 Feature 153
  lib/bloc/blocs.dart
  lib/bloc/despesa_image/bloc.dart
  lib/bloc/despesa_image/despesa_image_bloc.dart
  lib/bloc/despesa_image/despesa_image_event.dart
  lib/bloc/despesa_image/despesa_image_state.dart
  lib/core/service/url_launcher_service.dart
  lib/page/post/post_page.dart
  lib/widget/tile/despesa_tile.dart
  lib/widget/tile/despesa_tile_connected.dart
  test/bloc/despesa_image_bloc_test.dart
  test/bloc/event/despesa_image_event_test.dart
  test/bloc/state/despesa_image_state_test.dart
  test/mock.dart
  test/service/url_launcher_service_test.dart
  test/widget/despesa_tile_test.dart
  test/widget/goto_post_gesture_detector_test.dart
  test/widget/page/post_page_test.dart
  test/widget/page/timeline_page_test.dart
Labels: feature, pending tests, waiting review

#162 Feature 119
  lib/bloc/timeline/timeline_bloc.dart
  lib/bloc/timeline/timeline_event.dart
  lib/bloc/timeline/timeline_state.dart
  lib/core/constants.dart
  lib/core/service/url_launcher_service.dart
  lib/i18n/label.dart
  lib/page/favorite_posts/favorite_posts_page.dart
  lib/page/timeline/timeline_page.dart
  lib/page/timeline/widget/timeline.dart
  lib/repository/abstract/timeline_repository.dart
  lib/repository/concrete/firebase/firebase_timeline_repository.dart
  pubspec.lock
  pubspec.yaml
  test/bloc/event/timeline_event_test.dart
  test/bloc/state/timeline_state_test.dart
  test/bloc/timeline_bloc_test.dart
  test/mock.dart
  test/repository/firebase_timeline_repository_test.dart
  test/service/url_launcher_service_test.dart
  test/widget/page/timeline_page_test.dart
Labels: feature, waiting review, waiting tester

#177 Feature 158
  lib/bloc/flutter_bloc_delegate.dart
  lib/bloc/timeline/timeline_bloc.dart
  lib/core/service/locator.dart
  lib/core/service/performance_service.dart
  lib/core/service/services.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
  test/bloc/flutter_bloc_delegate_test.dart
  test/mock.dart
  test/widget/default_bottombar_test.dart
  test/widget/despesa_tile_test.dart
  test/widget/goto_post_gesture_detector_test.dart
  test/widget/my_app_test.dart
  test/widget/page/initial_page_test.dart
  test/widget/page/politic_profile_page_test.dart
  test/widget/page/politic_suggestion_page_test.dart
  test/widget/page/post_page_test.dart
  test/widget/page/search_politic_page_test.dart
  test/widget/page/signin_page_test.dart
  test/widget/page/signup_page_test.dart
  test/widget/page/timeline_page_test.dart
  test/widget/post_despesa_test.dart
Labels: waiting review

#179 Enhacement 169
  lib/repository/concrete/firebase/collection.dart
  lib/repository/concrete/firebase/firebase_favorite_posts_repository.dart
  lib/repository/concrete/firebase/firebase_post_repository.dart
  test/repository/firebase_favorite_posts_repository_test.dart
  test/repository/firebase_post_repository_test.dart
Labels: enhancement, waiting review, waiting tester

#180 Feature 149
  lib/i18n/label.dart
  lib/page/politic_profile/politic_profile_page.dart
  lib/page/politic_profile/widget/politic_activities.dart
  lib/page/politic_profile/widget/politic_profile.dart
  lib/page/user_profile/user_profile_page.dart
  lib/page/user_profile/widget/user_activities.dart
  lib/page/user_profile/widget/user_profile.dart
  lib/widget/tile/despesa_tile_connected.dart
  lib/widget/tile/proposta_tile_connected.dart
  pubspec.lock
  pubspec.yaml
  test/bloc/flutter_bloc_delegate_test.dart
  test/mock.dart
Labels: pending tests

#181 Enhacement 170
  lib/bloc/politic_profile/politic_profile_bloc.dart
  lib/bloc/politic_profile/politic_profile_event.dart
  lib/bloc/politic_profile/politic_profile_state.dart
  lib/page/politic_profile/politic_profile_page.dart
  lib/page/politic_profile/widget/politic_activities.dart
  lib/page/politic_profile/widget/politic_profile.dart
  lib/repository/abstract/politic_profile_repository.dart
  lib/repository/concrete/firebase/firebase_politic_profile_repository.dart
  test/bloc/event/politic_profile_event_test.dart
  test/bloc/flutter_bloc_delegate_test.dart
  test/bloc/politic_profile_bloc_test.dart
  test/bloc/state/politic_profile_state_test.dart
  test/mock.dart
  test/repository/firebase_politic_profile_repository_test.dart
  test/service/performance_service_test.dart
  test/widget/page/politic_profile_page_test.dart
Labels: enhancement, waiting review, waiting tester

#182 Feature 121
  lib/bloc/post/post_bloc.dart
  lib/bloc/post/post_event.dart
  lib/core/service/locator.dart
  lib/core/service/services.dart
  lib/core/service/share_service.dart
  lib/page/post/post_page.dart
  lib/page/post/post_page_connected.dart
  lib/widget/post/post_despesa.dart
  lib/widget/post/post_despesa_connected.dart
  lib/widget/post/post_proposta.dart
  lib/widget/tile/despesa_tile_connected.dart
  lib/widget/tile/proposta_tile_connected.dart
  pubspec.lock
  pubspec.yaml
  test/bloc/post_bloc_test.dart
  test/mock.dart
  test/service/share_service_test.dart
  test/widget/post_despesa_test.dart
  test/widget/post_proposta_test.dart
  test/widget/proposta_tile_test.dart
Labels: feature, waiting review, waiting tester

#190 Feature 164
  lib/bloc/blocs.dart
  lib/bloc/change_password/bloc.dart
  lib/bloc/change_password/change_password_bloc.dart
  lib/bloc/change_password/change_password_event.dart
  lib/bloc/change_password/change_password_state.dart
  lib/bloc/edit_profile/bloc.dart
  lib/bloc/edit_profile/edit_profile_bloc.dart
  lib/bloc/edit_profile/edit_profile_event.dart
  lib/bloc/edit_profile/edit_profile_state.dart
  lib/bloc/user/user_bloc.dart
  lib/bloc/user/user_event.dart
  lib/bloc/user/user_state.dart
  lib/core/exception/exceptions.dart
  lib/core/exception/wrong_password_exception.dart
  lib/core/routing/route_names.dart
  lib/i18n/label.dart
  lib/i18n/message.dart
  lib/page/change_password/change_password_page.dart
  lib/page/change_password/change_password_page_connected.dart
  lib/page/edit_profile/edit_profile_page.dart
  lib/page/edit_profile/edit_profile_page_connected.dart
  lib/page/pages.dart
  lib/page/user_profile/widget/personal_user_info.dart
  lib/repository/abstract/change_password_repository.dart
  lib/repository/abstract/edit_profile_repository.dart
  lib/repository/concrete/firebase/firebase_change_password_repository.dart
  lib/repository/concrete/firebase/firebase_edit_profile_repository.dart
  lib/repository/concrete/firebase/firebase_error_constants.dart
  lib/repository/concrete/firebase/firebase_signup_repository.dart
  lib/repository/concrete/repositories.dart
  lib/widget/default_bottombar.dart
  lib/widget/my_app_injections.dart
  scripts/runDev.sh
  scripts/runProd.sh
  test/bloc/change_password_bloc_test.dart
  test/bloc/edit_profile_bloc_test.dart
  test/bloc/event/change_password_event_test.dart
  test/bloc/event/edit_profile_event_test.dart
  test/bloc/state/change_password_state_test.dart
  test/bloc/state/edit_profile_state_test.dart
  test/bloc/state/user_state_test.dart
  test/bloc/user_bloc_test.dart
  test/mock.dart
  test/repository/firebase_change_password_repository_test.dart
  test/repository/firebase_edit_profile_repository_test.dart
  test/widget/page/change_password_page_test.dart
  test/widget/page/edit_profile_page_test.dart
Labels: feature, waiting review, waiting tester

#178 Feature 167
  .gitignore
  functions/index.js
  lib/bloc/user_profile/user_profile_bloc.dart
  lib/bloc/user_profile/user_profile_state.dart
  lib/enum/acao_type.dart
  lib/extension/formatters.dart
  lib/i18n/label.dart
  lib/main.dart
  lib/model/acao_usuario_model.dart
  lib/model/models.dart
  lib/page/user_profile/user_profile_page.dart
  lib/page/user_profile/widget/activities_list.dart
  lib/page/user_profile/widget/personal_user_info.dart
  lib/page/user_profile/widget/user_activities.dart
  lib/page/user_profile/widget/user_profile.dart
  lib/repository/abstract/user_profile_repository.dart
  lib/repository/concrete/firebase/collection.dart
  lib/repository/concrete/firebase/firebase_user_profile_repository.dart
  scripts/runTests.sh
  test/bloc/state/user_profile_state_test.dart
  test/bloc/user_profile_bloc_test.dart
  test/model/acao_usuario_model_test.dart
  test/repository/firebase_user_profile_repository_test.dart
  test/widget/page/user_profile_page_test.dart
  test/widget/personal_user_info_test.dart
Labels: feature

#193 Feature 189
  lib/bloc/signin/signin_bloc.dart
  lib/core/exception/email_not_verified_exception.dart
  lib/core/exception/exceptions.dart
  lib/i18n/message.dart
  lib/page/signin/signin_page.dart
  lib/repository/concrete/firebase/firebase_signin_repository.dart
  lib/repository/concrete/firebase/firebase_signup_repository.dart
  test/bloc/signin_bloc_test.dart
  test/repository/firebase_signin_repository_test.dart
  test/widget/page/signin_page_test.dart
Labels: feature, waiting review, waiting tester

#194 Enhacement 187
  assets/animations/PolisIntro.flr
  assets/animations/PolisLoading.flr
  lib/i18n/message.dart
  lib/page/crunching_data/crunching_data_page.dart
  lib/page/intro/intro_page.dart
  lib/page/pages.dart
  lib/page/politic_sugestion/politic_suggestion_page.dart
  lib/page/signin/signin_page.dart
  lib/page/signup/signup_page.dart
  lib/widget/centered_loading.dart
  pubspec.lock
  pubspec.yaml
  test/widget/page/change_password_page_test.dart
  test/widget/page/crunching_data_page_test.dart
  test/widget/page/politic_suggestion_page_test.dart
  test/widget/page/signup_page_test.dart
Labels: enhancement, pending ui, waiting review, waiting tester

#195 Feature 183
  lib/bloc/signin/signin_bloc.dart
  lib/bloc/signin/signin_event.dart
  lib/bloc/signin/signin_state.dart
  lib/core/validators.dart
  lib/i18n/label.dart
  lib/i18n/message.dart
  lib/page/signin/signin_page.dart
  lib/page/signin/widget/reset_password_form.dart
  lib/page/signup/signup_page.dart
  lib/repository/abstract/signin_repository.dart
  lib/repository/concrete/firebase/firebase_signin_repository.dart
  test/bloc/event/signin_event_test.dart
  test/bloc/signin_bloc_test.dart
  test/widget/page/signin_page_test.dart
  test/widget/reset_password_form_test.dart
Labels: feature, waiting review, waiting tester

#200 Enhancement 171
  lib/bloc/user/user_bloc.dart
  lib/i18n/message.dart
  lib/page/change_password/change_password_page.dart
  lib/page/edit_profile/edit_profile_page.dart
  lib/page/favorite_posts/favorite_posts_page.dart
  lib/page/politic_followers/politic_followers_page.dart
  lib/page/politic_profile/politic_profile_page.dart
  lib/page/politic_sugestion/politic_suggestion_page.dart
  lib/page/user_profile/user_profile_page.dart
  lib/page/user_profile/widget/user_profile.dart
  lib/widget/centered_loading.dart
  lib/widget/default_bottombar.dart
  lib/widget/loading.dart
  lib/widget/my_app.dart
  test/bloc/user_bloc_test.dart
  test/main_test.dart
  test/service/share_service_test.dart
  test/widget/default_bottombar_test.dart
  test/widget/page/change_password_page_test.dart
  test/widget/page/edit_profile_page_test.dart
  test/widget/page/politic_followers_page_test.dart
  test/widget/page/politic_suggestion_page_test.dart
  test/widget/page/search_politic_page_test.dart
  test/widget/page/user_following_politics_page_test.dart
  test/widget/page/user_profile_page_test.dart
  test/widget/politics_following_quantity_test.dart
  test/widget/utils.dart
Labels: pending tests

#199 adding better label to singular case
  lib/i18n/label.dart
  lib/page/timeline/widget/timeline.dart
  test/widget/page/timeline_page_test.dart
Labels: enhancement

#197 Feature 196
  lib/bloc/blocs.dart
  lib/bloc/tramitacao_proposta/tramitacao_proposta_bloc.dart
  lib/bloc/tramitacao_proposta/tramitacao_proposta_event.dart
  lib/bloc/tramitacao_proposta/tramitacao_proposta_state.dart
  lib/core/routing/route_names.dart
  lib/i18n/label.dart
  lib/model/models.dart
  lib/model/proposta_model.dart
  lib/model/tramitacao_proposta_model.dart
  lib/page/pages.dart
  lib/page/tramitacao_proposta/tramitacao_proposta_page.dart
  lib/page/tramitacao_proposta/tramitacao_proposta_page_connected.dart
  lib/repository/abstract/tramitacao_proposta_repository.dart
  lib/repository/concrete/firebase/firebase.dart
  lib/repository/concrete/firebase/firebase_tramitacao_proposta_repository.dart
  lib/repository/concrete/repositories.dart
  lib/widget/my_app_injections.dart
  lib/widget/post/post_proposta.dart
  lib/widget/timeline_tile.dart
  test/bloc/event/tramitacao_proposta_event_test.dart
  test/bloc/state/tramitacao_proposta_state_test.dart
  test/bloc/tramitacao_proposta_bloc_test.dart
  test/mock.dart
  test/model/proposta_model_test.dart
  test/model/tramitacao_proposta_model_test.dart
  test/widget/page/tramitacao_proposta_page_test.dart
Labels: feature, waiting review, waiting tester

#205 Enhancement 204
  lib/i18n/label.dart
  lib/widget/post/post_proposta.dart
  lib/widget/tile/proposta_tile.dart
  test/widget/post_proposta_test.dart
  test/widget/proposta_tile_test.dart
Labels: enhancement

#206 Enhancement 198
  lib/i18n/message.dart
  lib/page/intro/intro_page.dart
Labels: enhancement

#202 Feature 53
  android/app/src/dev/google-services.json
  lib/core/abstract/polis_google_auth_provider.dart
  lib/enum/auth_provider.dart
  lib/model/user_model.dart
  lib/page/edit_profile/edit_profile_page.dart
  lib/page/initial/initial_page.dart
  lib/page/user_profile/widget/user_profile.dart
  lib/repository/concrete/firebase/firebase_signin_repository.dart
  lib/repository/concrete/firebase/firebase_signup_repository.dart
  lib/repository/concrete/firebase/firebase_user_repository.dart
  lib/widget/my_app_injections.dart
  test/core/polis_google_auth_provider_test.dart
  test/mock.dart
  test/model/user_model_test.dart
  test/repository/firebase_signin_repository_test.dart
  test/repository/firebase_user_repository_test.dart
  test/widget/page/edit_profile_page_test.dart
  test/widget/page/initial_page_test.dart
  test/widget/page/signin_page_test.dart
Labels: feature, waiting review, waiting tester

#207 Enhacement 129
  assets/animations/app_error.flr
  lib/i18n/message.dart
  lib/page/favorite_posts/favorite_posts_page.dart
  lib/page/politic_profile/politic_profile_page.dart
  lib/page/politic_sugestion/politic_suggestion_page.dart
  lib/page/search_politic/search_politic_page.dart
  lib/page/user_following_politics/user_following_politics_page.dart
  lib/page/user_profile/user_profile_page.dart
  lib/widget/error_container.dart
  test/widget/page/favorite_posts_page_test.dart
  test/widget/page/politic_profile_page_test.dart
  test/widget/page/search_politic_page_test.dart
  test/widget/page/user_following_politics_page_test.dart
  test/widget/page/user_profile_page_test.dart
Labels: enhancement

#176 puting ads
  lib/core/constants.dart
  lib/core/keys.dart
  lib/core/service/ad_service.dart
  lib/core/service/locator.dart
  lib/i18n/message.dart
  lib/main.dart
  lib/page/change_password/change_password_page.dart
  lib/page/crunching_data/crunching_data_page.dart
  lib/page/edit_profile/edit_profile_page.dart
  lib/page/initial/initial_page.dart
  lib/page/intro/intro_page.dart
  lib/page/politic_profile/widget/politic_action_buttons.dart
  lib/page/search_politic/widgets/search_politics.dart
  lib/page/search_politic/widgets/search_politics_list.dart
  lib/page/signin/signin_page.dart
  lib/page/signup/signup_page.dart
  lib/page/timeline/widget/timeline.dart
  lib/page/timeline/widget/timeline_skeleton.dart
  lib/page/user_following_politics/widget/following_politics_list.dart
  lib/page/user_following_politics/widget/following_politics_search.dart
  lib/page/user_profile/widget/user_profile.dart
  lib/repository/concrete/firebase/firebase_signin_repository.dart
  lib/widget/card_base.dart
  lib/widget/default_bottombar.dart
  lib/widget/post/post_despesa.dart
  lib/widget/post/post_proposta.dart
  pubspec.lock
  pubspec.yaml
  test/bloc/politic_profile_bloc_test.dart
  test/bloc/timeline_bloc_test.dart
  test/main_test.dart
  test/mock.dart
  test/model/tramitacao_proposta_model_test.dart
  test/repository/firebase_signin_repository_test.dart
  test/repository/firebase_tramitacao_proposta_repository_test.dart
  test/service/ad_service_test.dart
  test/widget/default_bottombar_test.dart
  test/widget/despesa_tile_test.dart
  test/widget/following_politics_search_test.dart
  test/widget/page/change_password_page_test.dart
  test/widget/page/edit_profile_page_test.dart
  test/widget/page/intro_page_test.dart
  test/widget/page/search_politic_page_test.dart
  test/widget/page/signin_page_test.dart
  test/widget/page/signup_page_test.dart
  test/widget/page/timeline_page_test.dart
  test/widget/page/user_following_politics_page_test.dart
  test/widget/page/user_profile_page_test.dart
  test/widget/politic_action_buttons_test.dart
  test/widget/post_despesa_test.dart
  test/widget/post_proposta_test.dart
  test/widget/proposta_tile_test.dart
  test/widget/timeline_tile_test.dart
Labels: WIP, debate first, experimental, feature

#210 Enhacement 209
  lib/bloc/timeline/timeline_bloc.dart
  lib/bloc/timeline/timeline_state.dart
  lib/i18n/label.dart
  lib/i18n/message.dart
  lib/page/timeline/timeline_page.dart
  lib/repository/concrete/firebase/firebase_timeline_repository.dart
  pubspec.lock
  pubspec.yaml
  test/bloc/search_politic_bloc_test.dart
  test/bloc/timeline_bloc_test.dart
  test/widget/page/timeline_page_test.dart
Labels: enhancement, waiting review, waiting tester
