Repository gladguys/polis, pull requests merged in 2020-06, with the labels that each got.

#375 getting the right id
  lib/core/repository/concrete/firebase/firebase_post_repository.dart
Labels: bug

#371 Enhacement 369
  lib/widget/post/post_proposta.dart
  lib/widget/tag/tag_despesa.dart
  lib/widget/tag/tag_proposta.dart
  lib/widget/tile/despesa_tile.dart
  lib/widget/tile/favorite_despesa_tile.dart
  lib/widget/tile/favorite_proposta_tile.dart
  lib/widget/tile/politic_despesa_tile.dart
  lib/widget/tile/politic_proposta_tile.dart
  lib/widget/tile/proposta_tile.dart
  test/page/politic_profile_page_test.dart
  test/page/post_page_test.dart
  test/page/timeline_page_test.dart
  test/widget/favorite_proposta_tile_test.dart
  test/widget/politic_proposta_tile_test.dart
  test/widget/post_proposta_test.dart
  test/widget/proposta_tile_test.dart
Labels: enhancement, waiting review, waiting tester

#376 Bug 372
  lib/core/repository/concrete/firebase/firebase_politico_repository.dart
  test/core/repository/firebase_politico_repository_test.dart
Labels: bug

#392 Improve loading last activities
  lib/page/politic_profile/widget/politic_activities.dart
  lib/page/politic_profile/widget/politic_profile.dart
  lib/page/user_profile/widget/user_profile.dart
  lib/widget/tile/politic_despesa_tile.dart
  test/page/politic_profile_page_test.dart
  test/widget/politic_despesa_tile_test.dart
Labels: enhancement, pending tests

#396 adding single child scroll view to enable scrolling on this page
  lib/page/comparativo_ranking_despesas/widget/resultados_ranking.dart
Labels: bug, waiting review, waiting tester

#395 Refactor favorite
  lib/bloc/post/post_bloc.dart
  lib/bloc/post/post_state.dart
  lib/core/domain/model/despesa_model.dart
  lib/core/repository/concrete/firebase/firebase.dart
  lib/widget/tile/despesa_tile.dart
  lib/widget/tile/favorite_despesa_tile.dart
  lib/widget/tile/favorite_despesa_tile_connected.dart
  lib/widget/tile/favorite_proposta_tile.dart
  lib/widget/tile/favorite_proposta_tile_connected.dart
  lib/widget/tile/proposta_tile.dart
  pubspec.lock
  test/bloc/post_bloc_test.dart
  test/widget/despesa_tile_test.dart
  test/widget/proposta_tile_test.dart
Labels: bug, waiting review, waiting tester
